- hosts: all
  gather_facts: yes
  become: true
  
  vars_files:
    - vars/main.yml
  
  pre_tasks:

    - name: Add timestamps to history
      lineinfile: 
        dest: /root/.bash_profile
        state: present
        line: 'HISTTIMEFORMAT="%m/%d/%y %T "' 

    - name: Configure MOTD
      template:
        src: 'motd.j2'
        dest: '/etc/motd'
        owner: 'root'
        group: 'root'
        mode: '0744'

    - name: Insert include into /root/.bash_logout
      lineinfile:
        dest: /root/.bash_logout
        line: cat logout.txt
        state: present

    - name: Configure logout text
      template:
        src: 'logout.j2'
        dest: '/root/logout.txt'
        owner: 'root'
        group: 'root'
        mode: '0744'

    - name: Install VIM & Git
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - vim
        - git

    - name: Create FPM user(s)
      user:
        name: "{{ item.fpm }}"
        state: present
        system: yes
      with_items: 
        - "{{ vhosts }}"    

  roles:

    - ansible-role-repo-epel
    - ansible-role-repo-remi
    - ansible-role-nginx
    - ansible-role-php
    - ansible-role-mysql

  post_tasks:

    - name: Create /var/www/{{ item.site }} directory
      file: path=/var/www/{{ item.site }} state=directory group=nginx mode=755
      with_items:
        - "{{ vhosts }}"
 
    - name: Create vhost file from template
      template: src=templates/vhost.j2 dest=/etc/nginx/conf.d/{{ item.site }}.conf
      with_items:
        - "{{ vhosts }}"

    - name: Create pool file from template
      template: src=templates/pool.j2 dest=/etc/php-fpm.d/{{ item.site }}.conf
      with_items:
        - "{{ vhosts }}"

    - name: Allow Ports 80 & 443 in Firewalld
      firewalld:
        immediate: yes
        service: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - http
        - https

    - name: Remove /etc/php-fpm.d/www.conf
      file:
        name: /etc/php-fpm.d/www.conf
        state: absent

    - name: Correct /var/www/ Permissions
      file:
        name: /var/www
        group: nginx
        mode: 1517

    - name: Correct Socket Ownership
      file:
        name: /var/run/php-fpm/
        group: nginx
        mode: 1517

    - name: Start PHP-FPM
      service: 
        name: php-fpm
        state: restarted

    - name: Clone Git repo
      git: 
        clone: yes
        dest: /var/www/{{  item.site }}
        repo: "{{ item.git }}"
        force: yes
      with_items:
        - "{{ vhosts }}

    - name: Restart Nginx
      service: 
        name: nginx
        state: restarted"
