---
- src: https://github.com/geerlingguy/ansible-role-repo-epel.git
- src: https://github.com/geerlingguy/ansible-role-repo-remi.git
- src: https://github.com/geerlingguy/ansible-role-mysql.git
- src: https://github.com/geerlingguy/ansible-role-nginx.git
- src: https://github.com/geerlingguy/ansible-role-php.git
